# Generated by Django 5.0.1 on 2024-02-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapi', '0002_alter_author_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
